# Pod autoscaler works with gpu-optimizer
apiVersion: autoscaling.aibrix.ai/v1alpha1
kind: PodAutoscaler
metadata:
  name: podautoscaler-simulator-llama2-7b-a100
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simulator-llama2-7b-a100
  metricsSources: 
    - endpoint: aibrix-gpu-optimizer.aibrix-system.svc.cluster.local:8080
      path: /metrics/default/simulator-llama2-7b-a100
      metric: "vllm:deployment_replicas"
  targetValue: "1"