# this manifest is for public stable release.
# Please override the tag with latest stable tags.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

images:
- name: quay.io/kuberay/operator
  newName: aibrix/kuberay-operator
  newTag: v1.2.1-patch
- name: envoyproxy/envoy
  newTag: distroless-v1.31.0
- name: busybox
  newTag: stable
- name: redis
  newTag: latest
- name: aibrix/plugins
  newTag: v0.2.0-rc.1
- name: aibrix/users
  newTag: v0.2.0-rc.1
- name: aibrix/controller-manager
  newTag: v0.2.0-rc.1
- name: aibrix/runtime
  newTag: v0.2.0-rc.1
