apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
  namespace: aibrix-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: aibrix-system
spec:
  gatewayClassName: aibrix-eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: aibrix-system
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    provider:
      type: Kubernetes
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableEnvoyPatchPolicy: true   
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: gateway-plugins-extension-policy
  namespace: aibrix-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: aibrix-eg
  extProc:
    - backendRefs:
        - name: aibrix-gateway-plugins
          port: 50052
      processingMode:
        request: {}
        response: 
          body: Streamed
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: epp
  namespace: aibrix-system
spec:
  type: "JSONPatch"
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: aibrix-eg
  jsonPatches:
  - type: type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: "aibrix-system/aibrix-eg/http"
    operation:
      op: add
      path: "/virtual_hosts/0/routes/0"
      value:
        name: original_route
        match:
          prefix: "/"
          # headers:
          #   # update ip address as needed and in production this config is not needed as backend will derive the pod ip
          #   - name: "target-pod"
          #     string_match:
          #       exact: "10.244.1.3:8000"
        route:  
          cluster: original_destination_cluster
          timeout: 1000s  # Increase route timeout
        typed_per_filter_config:
          "envoy.filters.http.ext_proc/envoyextensionpolicy/aibrix-system/gateway-plugins-extension-policy/extproc/0":
            "@type": "type.googleapis.com/envoy.config.route.v3.FilterConfig"
            "config": {}
  - type: "type.googleapis.com/envoy.config.cluster.v3.Cluster"
    name: "envoy-patch-policy-override2"
    operation:
      op: add
      path: ""
      value:
        name: original_destination_cluster
        type: ORIGINAL_DST  
        original_dst_lb_config:
          use_http_header: true
          http_header_name: "target-pod"
        connect_timeout: 6s
        lb_policy: CLUSTER_PROVIDED
        dns_lookup_family: V4_ONLY
  