resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- controller-manager
# For each CRD, "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the Project itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- orchestration/orchestration_rayclusterfleet_editor_role.yaml
- orchestration/orchestration_rayclusterfleet_viewer_role.yaml
- orchestration/orchestration_rayclusterreplicaset_editor_role.yaml
- orchestration/orchestration_rayclusterreplicaset_viewer_role.yaml
- model/model_modeladapter_editor_role.yaml
- model/model_modeladapter_viewer_role.yaml
- autoscaling/autoscaling_podautoscaler_editor_role.yaml
- autoscaling/autoscaling_podautoscaler_viewer_role.yaml
# other components
- gateway
