apiVersion: v1
kind: Service
metadata:
  name: gpu-optimizer
  namespace: aibrix-system
spec:
  selector:
    app: gpu-optimizer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP