apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../dependency

patches:
- path: envoy_gateway_patch.yaml

images:
- name: envoyproxy/gateway
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/envoyproxy/gateway
  newTag: v1.2.8