kind: Kustomization

resources:
- ../../dev/manager

images:
- name: aibrix/controller-manager
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/controller-manager
  newTag: v0.2.0-rc.2