name: Python Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'python/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd python/aibrix
          python -m pip install --upgrade pip
          pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install --no-root --with dev
      - name: Run Ruff
        run: |
          cd python/aibrix
          python -m ruff check .
          python -m ruff format --check .
      - name: Run mypy
        run: |
          cd python/aibrix
          python -m mypy .
      - name: Run Test
        run: |
          cd python/aibrix/tests
          python -m pytest .
